<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <None Include="paket.references" />
    <Compile Include="Domain.Tests.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Shared\Shared.fsproj" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
